# Matrices

In [1]:
row = [1,2,3]
row

[1, 2, 3]

In [2]:
col = [[1],[2],[3]]

In [3]:
M = [[1,2,3],[4,5,6],[7,8,9]]

In [4]:
M[1][1]

5

In [5]:
M[0][0]

1

In [6]:
M[0]

[1, 2, 3]

In [7]:
2 * M

[[1, 2, 3], [4, 5, 6], [7, 8, 9], [1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [8]:
import numpy as np

In [10]:
M = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [11]:
M

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
M = np.array([[1,2,3],[4,5,6],[7,8,9]], dtype=float)
M

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [14]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [15]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [16]:
np.shape(M)

(3, 3)

In [19]:
A = np.array([[1,2],[3,4]])
B = np.array([[3,0],[-1,1]])

In [20]:
A + B

array([[4, 2],
       [2, 5]])

In [21]:
A * B #producto tensorial

array([[ 3,  0],
       [-3,  4]])

In [22]:
A.dot(B) #producto matricial

array([[1, 2],
       [5, 4]])

In [23]:
A.transpose()

array([[1, 3],
       [2, 4]])

In [24]:
A.trace()

5

In [25]:
np.linalg.matrix_rank(A)

2

In [26]:
np.linalg.matrix_power(A,5)

array([[1069, 1558],
       [2337, 3406]])

In [27]:
np.linalg.det(A)

-2.0000000000000004

In [28]:
np.linalg.inv(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [29]:
np.linalg.inv(A).dot(A)

array([[1.00000000e+00, 0.00000000e+00],
       [1.11022302e-16, 1.00000000e+00]])